### ISSUE TITLE
List of languages

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/renamer#10]
0.85 & 0.90
I install and activate the plugin, but don't have defined yet the languages to display (via Config > > Plugins > Renamer).
I go to Admin > Renamer : I can add an overload in any language. I get a list of all languages of GLPI !

I go back the the plugin's config, add a language to display, then suppress it. In Admin > Renamer, the situation is now correct : the list of languages is empty.

**Comment by orthagh** [comment]
Seems ok for me.
When no filter on language, list all languages, no ?

**Comment by blerohellec** [comment]
OK. You can close

**Comment by blerohellec** [comment]
To be coherent, the 2nd point has to be looked after : 
"I go back the the plugin's config, add a language to display, then suppress it. In Admin > Renamer, the situation is now correct : the list of languages is empty."
In this case, the list of languages should be again 'All languages'.

**Comment by orthagh** [comment]
done

**Comment by blerohellec** [comment]
Perfect. Thx
