### ISSUE TITLE
(0.84-1.5_beta2 && 0.90) Bug : Wrong encoding display

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/renamer#12]
In a GLPI in french, if you find '..' string in the renamer plugin for rewrite string, the plugin display : 

*Checking write permissions for session files* || *Test d'��criture des fichiers de sessions* <-- wrong encoding display (é -> ��)

**Comment by orthagh** [comment]
strange, not in my instance.

You write ".." in search field, right ?
