### ISSUE TITLE
Display of renamer plugin from a user profile

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/renamer#16]
From Simplified interface profile the plugin renamer is present : not a good idea & display errors : 

2015-11-05 14:03:39 [2@P365]
  **\* PHP Notice(8): Undefined index: right
  Backtrace :
  plugins\renamer\inc\profile.class.php:100  
  plugins\renamer\inc\profile.class.php:133          PluginRenamerProfile->showForm()
  inc\commonglpi.class.php:469                       PluginRenamerProfile::displayTabContentForItem()
  ajax\common.tabs.php:91                            CommonGLPI::displayStandardTab()

**Comment by trasher** [comment]
This plugin is replaced with a feature in GLPI core: https://github.com/glpi-project/glpi/pull/5907
