### ISSUE TITLE
Cant install Renamer

### ISSUE THREAD

**Issue by seville2612** [pluginsGLPI/renamer#17]
Hi. I can`t install the plugin Renamer
The warning is appeared
Please give write permission to the 'locales' folder of Glpi
/glpi/locales has already 777 permission for apache
chown apache:apache -R locales/
chmod -R 777 locales/
There is the same for renamer/locales

**Comment by seville2612** [comment]
upd:
permission for /glpi/locales wasnt set.
all fine now

**Comment by seville2612** [comment]
But the error is appeared
[http://c2n.me/3yTlnHc.jpg](url)

**Comment by GoempieK** [comment]
How did you change the permission for /glpi/locales?

**Comment by trasher** [comment]
The provided link is dead... And as the initial issue has been solved, I close the ticket for now. Fell free to open another ticket with details if you still ave an error.

**Comment by mail2remith** [comment]
Hi All,

I am facing Error when installing glp renamer plugin from webserver to ubuntu server.I had tryed all above mentioned methods.But no luck.PFA error screen shot
![glp_error](https://user-images.githubusercontent.com/3740286/61455884-5ba6a000-a982-11e9-9a60-ed0981d409a4.PNG)
