### ISSUE TITLE
Check if gettext is installed

### ISSUE THREAD

**Issue by wawax** [pluginsGLPI/renamer#2]
I've installed the plugin without having gettext on the sever
The plugin should check it at installation, and refuse to install itself in this case

**Comment by orthagh** [comment]
I don't like very much this dependencies.
Sys Gettext is needed for compile po in mo files.

Another problem is that plugin isn't compatible with windows web servers.
It requires gettext unix tools.

**Comment by orthagh** [comment]
See https://github.com/oscarotero/Gettext

pure php gettext library (support compilation)

**Comment by orthagh** [comment]
Another one : 
https://github.com/phpmo/php.mo

more simple, i'll test to implement it.
I think we need to rewrite with first proposal soon

**Comment by wawax** [comment]
I'm also interested for implementing on of these library for genericobject

**Comment by orthagh** [comment]
Second one don't work.
First seems ok
