### ISSUE TITLE
0.84 : Ne pas échapper l'appostrophe dans le message à l'utilisateur (bug mineur)

### ISSUE THREAD

**Issue by Manu1400** [pluginsGLPI/renamer#3]
Message après le changement de la traduction "mails" en "mail's" : 

```
'mails' remplacé par 'mail\'s'
```

**Comment by Manu1400** [comment]
Et la valeur "1&0.1" donne "<ancienne valeur> remplacé par '1'".

**Comment by trasher** [comment]
This plugin is replaced with a feature in GLPI core: https://github.com/glpi-project/glpi/pull/5907
