### ISSUE TITLE
Release for GLPI 9.2

### ISSUE THREAD

**Issue by roshanroche** [pluginsGLPI/renamer#34]
Dear All,
It will be a great help if we have a release for GLPI 9.2 version.

**Comment by trasher** [comment]
Te way this plugin works is very ugly; must be entirely reworked before anything from my point of view (and I do not have time for that myself).

**Comment by GuiGuiSoft** [comment]
Hello,
Unfortunately I can not help, but I am very interested too for GLPI 9.2.1+
regards.

**Comment by trasher** [comment]
Just to resume; following issues must be fixed for a new release:
- [ ] #32,
- [ ] #18 (the one that requires a lot of work),
- [ ] certainly  #29 as well.

**Comment by trasher** [comment]
This plugin is replaced with a feature in GLPI core: https://github.com/glpi-project/glpi/pull/5907
