### ISSUE TITLE
Internet server error

### ISSUE THREAD

**Issue by imanou10** [pluginsGLPI/renamer#37]
Bonjour 
Voici le message d'erreur depuis la migration en 9.4 et malgré du plugin dédié au 9.4.
"internal server error" lorsque j'essaye de rechercher un terme.
En vous remerciant pour votre aide

**Comment by OfficeLink** [comment]
Unfortunately this plugin is not compatible with the new version of GLPI. A complete overhaul is necessary.
I'm hoping someone will resume the development of this plugin.
Hugs.

**Comment by trasher** [comment]
This plugin is replaced with a feature in GLPI core: https://github.com/glpi-project/glpi/pull/5907
