### ISSUE TITLE
Pb with msgstr ""

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/renamer#7]
v0.85 & 0.90
Given a .po file containing a msgstr "" -> examples
- 0.85, en_GB.po, msgid "Create a sub project from this project"
- 0.90, es_ES.po, msgid "Keep tabs replaced by the ticket timeline"

When overloading any word in this language (let's say en_GB), the .po file is re-written in /locales but the quotes disappear behind msgstr.
And this makes the compilation fail, ie the .mo file is not generated.
It can be clearly seen by running the msgfmt command, on command line, on the re-written .po file. It results in errors refering to lines where we previously had msgstr "".

At least, it would be nice to display an error msg when compiling fails.

**Comment by orthagh** [comment]
I can't replicate systematically.
Sometime (in my first test), it effectively fails and msgstr is totally empty
Sometime not, compilation works and my po file contains my override.

In all of my lasts tests, compilation always succeeds so i don't catch any error message.

Have you a method to always do a failed compilation ?

**Comment by orthagh** [comment]
after a failed test, output of msgfmt is empty, no error triggered by command...

**Comment by blerohellec** [comment]
Great and Thx
