### ISSUE TITLE
Pb with restore a plural

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/renamer#8]
v0.85, 0.90 (and previous)
Overload a msgid and its plural with the same word 
msgid "Ticket" -> TicketX
msgid_plural "Tickets" -> TicketX
And restore one of them -> both are changed back !

Or overload msgid "Ticket" to Tickets (= msgid_plural) and restore -> msgid_plural is now Ticket.

**Comment by blerohellec** [comment]
Same with context
Overload msgctxt 'priority', msgid 'High' -> HighX
and msgctxt 'urgency', msgid 'High' -> HighX
Restore one of them -> both are changed back

**Comment by trasher** [comment]
This plugin is replaced with a feature in GLPI core: https://github.com/glpi-project/glpi/pull/5907
